---

name: Jenkins Deployment via SSH Port Forwarding

# on:
#   workflow_run:
#     workflows: ["Terraform Deployment"]
#     types:
#       - completed

on:
  push:
    branches:
      - task_xxx # Replace with your branch name to test GitHub Actions without pushing to the dev branch
      - task_4
      - dev

jobs:
  deploy-jenkins:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install SSH client and configure port forwarding
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        BASTION_HOST: ${{ vars.BASTION_HOST }}
        K3S_SERVER_HOST: ${{ vars.K3S_SERVER_HOST }} 
        EC2_USER: ${{ vars.EC2_USER }}

      run: |
        # Start SSH agent and add the SSH key
        eval "$(ssh-agent -s)"
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
        # Start SSH port forwarding in the background
        # Create .ssh directory if it doesn't exist
        mkdir -p ~/.ssh
        # Optionally, initialize the known_hosts file
        touch ~/.ssh/known_hosts
        # ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=~/.ssh/known_hosts -f -N -A -J "$EC2_USER@$BASTION_HOST" "$EC2_USER@$K3S_SERVER_HOST" -L 6443:localhost:6443 
        ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=~/.ssh/known_hosts -A -J "$EC2_USER@$BASTION_HOST" "$EC2_USER@$K3S_SERVER_HOST" -L 6443:localhost:6443 

    # - name: Set up Kubernetes config
    #   env:
    #     KUBECONFIG: ${{ vars.K3S_CONFIG }}
    #   run: |
    #     # Download your k3s.yml from the EC2 instance
    #     scp -J "$EC2_USER@$BASTION_HOST" "$EC2_USER@$K3S_SERVER_HOST:/etc/rancher/k3s/k3s.yml" $KUBECONFIG
    - name: Deploy Jenkinss
      env:
        KUBECONFIG_FILE: ${{ vars.K3S_CONFIG }}
      run: |
        kubectl apply -f jenkins-volume.yaml
        kubectl apply -f jenkins-sa.yaml
        helm repo add jenkins https://charts.jenkins.io
        helm repo update
        helm install jenkins -n jenkins -f jenkins-values.yaml jenkins/jenkins