name: Terraform Deployment

on:
  pull_request:
    branches:
      - task_1
  push:
    branches:
      - task_1

jobs:
  terraform_init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.6

      - name: Terraform Init
        run: terraform init
        working-directory: task_1

  terraform_check:
    runs-on: ubuntu-latest
    needs: terraform_init
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.6

      - name: Terraform Plan
        run: terraform fmt
        working-directory: task_1

  terraform_plan:
    runs-on: ubuntu-latest
    needs: terraform_check
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.6

      - name: Terraform Plan
        run: terraform 
        working-directory: task_1

  terraform_apply:
    runs-on: ubuntu-latest
    needs: terraform_plan
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.6

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: task_1